### ISSUE TITLE
website and wiki

### ISSUE THREAD

**Issue by frakier** [team-abnormals/announcements#2]
any plans for the website.
For instance our modpack updated today and I have bees with color stripes. So I go to the Abnormals website... click Buzzier Bees to get some info and I am sent to curseforge... with no info either. Not just no info on the suddenly colored striped bees but nothing really on the mod at all. So I go to discord... click the buzzier-bees... not a wiki just discussion.
You all make some amazing mods but you miss the boat on documentations and by extension self promotion. Get something going so I can brag on you more with actual links.

**Comment by bageldotjpg** [comment]
1. Documentation is in progress, but it takes time.
2. That isn't a feature from our mods so thats also why you can't find anything on it.
3. This is not the place to bring up things like this even if it hasn't been answered.
