### ISSUE TITLE
Server crashes when killing the ender dragon

### ISSUE THREAD

**Issue by sutepu-chan** [team-abnormals/announcements#4]
[crash-reports_crash-2022-04-06_10.26.33-server.txt](https://github.com/team-abnormals/announcements/files/8426085/crash-reports_crash-2022-04-06_10.26.33-server.txt)

**Comment by bageldotjpg** [comment]
Completely incorrect repository for this, and its already reported on the endergetic repository https://github.com/team-abnormals/endergetic/issues/

**Comment by sutepu-chan** [comment]
Thanks
