### ISSUE TITLE
Where wiki?

### ISSUE THREAD

**Issue by BlackAures1** [team-abnormals/announcements#5]
Hello. Add a normal description to your mods, please.

**Comment by bageldotjpg** [comment]
Wiki is in development, but it takes a lot of work and we also have to port mods to more recent versions in addition to adding contents. Slowly but surely, sorry about that.

**Comment by BlackAures1** [comment]
At least it's not a wiki. Just a trivial description of the mods. I honestly can't figure out what 90% of your mods are about from the description x)

**Comment by bageldotjpg** [comment]
Each curseforge has a short description of the mods. For additional information for the time being you can stop by our discord server

**Comment by BlackAures1** [comment]
I'm just saying that for me personally, when creating modpacks, the content of your mods is the hardest thing to understand from the page. I can't help but think that this is done intentionally so that people download the mod/join discord to find out if this mod should be added to the modpack. This is not a nice thing to say the least.

**Comment by BlackAures1** [comment]
How's it going?
