### ISSUE TITLE
Homepage suggestion: Wiki pages for each mod

### ISSUE THREAD

**Issue by ehx-v1** [team-abnormals/announcements#6]
When you look at the CurseForge pages, all the Abnormals mods have very minimal info. For this reason, I was thinking that the Team Abnormals page has a Wiki page for each mod, where the features are explained in more detail. It was a surprise that that's not the case, and I would suggest adding it.

The way I would imagine it working is that the Mods section gets a subpage for each mod, the links to which replace the Curseforge links in the pictures. At the top of the page, there would be a CurseForge button as often seen on other sites around the Internet, and the page would then go on with a detailed description of each change and item. For example, the Berry Good mod would have sections about berry pips, Sweet Berries (mentioning that they can be cooked and how they can be turned into pips), Glow Berries (mentioning that they function like Sweet Berries and additionally give the Glowing effect), changes to Fox held items and any feature I'm not aware of (with very small features being collapsed into one "Other changes" section).

**Comment by bageldotjpg** [comment]
Documentation has been missing and a work in progress for a long time, it is planned but there is a lot that needs to be documented and we do not have a lot of time.
